version: "3.9"
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./data:var/lib/clickhouse

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      clickhouse:
        condition: service_healthy