// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	GetVideoByID(ctx context.Context, id int32) (Video, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
}

var _ Querier = (*Queries)(nil)
